// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qmtakzxwkbcmglisqcow.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFtdGFrenh3a2JjbWdsaXNxY293Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc4NjY1NzcsImV4cCI6MjA3MzQ0MjU3N30.Yi2rC4_TbFGO1Gb0F0_rrKpl37j4tqYey6-RccoDkP8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});